// Explicit local number facts for each integer from 1 to 500.
// Special facts are preferred first; generic facts are fallback for remaining numbers.

export const specialNumberFacts = {
  1: { fact: "1 is the only positive integer that is neither prime nor composite.", special: true },
  2: { fact: "2 is the only even prime number.", special: true },
  3: { fact: "3 is the first odd prime number.", special: true },
  4: { fact: "4 is the first nontrivial perfect square.", special: true },
  5: { fact: "5 is the number of fingers on one hand.", special: true },
  6: { fact: "6 is the smallest perfect number because 1 + 2 + 3 equals 6.", special: true },
  7: { fact: "7 is a prime number often called lucky.", special: true },
  8: { fact: "8 is 2 cubed.", special: true },
  9: { fact: "9 is the square of 3.", special: true },
  10: { fact: "10 is the base of the decimal number system.", special: true },
  11: { fact: "11 is the smallest two-digit prime number.", special: true },
  12: { fact: "12 is a highly composite number with six positive divisors.", special: true },
  13: { fact: "13 is a prime number often linked with superstition.", special: true },
  16: { fact: "16 is the square of 4.", special: true },
  18: { fact: "18 is the legal adult age in many countries.", special: true },
  20: { fact: "20 is the number of fingers and toes on a typical human body.", special: true },
  21: { fact: "21 is a Fibonacci number and a triangular number.", special: true },
  24: { fact: "24 is the number of hours in a day.", special: true },
  25: { fact: "25 is the square of 5.", special: true },
  27: { fact: "27 is 3 cubed.", special: true },
  28: { fact: "28 is a perfect number because 1 + 2 + 4 + 7 + 14 equals 28.", special: true },
  30: { fact: "30 is the number of days in several calendar months.", special: true },
  32: { fact: "32 equals 2 to the 5th power.", special: true },
  36: { fact: "36 is the square of 6.", special: true },
  40: { fact: "40 is common in periods of time, like 40 weeks of pregnancy.", special: true },
  42: { fact: "42 is popularly known as the answer to life in science fiction.", special: true },
  49: { fact: "49 is the square of 7.", special: true },
  50: { fact: "50 is exactly half of 100.", special: true },
  60: { fact: "60 is the base of historical time measurement for minutes and seconds.", special: true },
  64: { fact: "64 is both 8 squared and 2 to the 6th power.", special: true },
  65: { fact: "65 is the product of 5 and 13.", special: true },
  72: { fact: "72 has many divisors and appears in geometry and time cycles.", special: true },
  81: { fact: "81 is the square of 9.", special: true },
  88: { fact: "88 is often used as a symbol of good fortune in some cultures.", special: true },
  89: { fact: "89 is a prime number and also a Fibonacci number.", special: true },
  90: { fact: "90 is a right angle in degree measure.", special: true },
  96: { fact: "96 is divisible by 12 and 8, making it useful in fractions.", special: true },
  99: { fact: "99 is one less than 100 and has repeating digits.", special: true },
  100: { fact: "100 is the square of 10.", special: true },
  108: { fact: "108 is a culturally significant number in several traditions.", special: true },
  111: { fact: "111 is a repdigit made from three 1s.", special: true },
  120: { fact: "120 is 5 factorial, written as 5!.", special: true },
  121: { fact: "121 is the square of 11.", special: true },
  125: { fact: "125 is equal to 5 cubed.", special: true },
  128: { fact: "128 is 2 to the 7th power.", special: true },
  144: { fact: "144 is 12 squared and also a Fibonacci number.", special: true },
  169: { fact: "169 is the square of 13.", special: true },
  180: { fact: "180 is the sum of angles in a triangle in Euclidean geometry.", special: true },
  196: { fact: "196 is the square of 14.", special: true },
  200: { fact: "200 is double 100.", special: true },
  225: { fact: "225 is the square of 15.", special: true },
  243: { fact: "243 is 3 to the 5th power.", special: true },
  256: { fact: "256 is equal to 2 to the 8th power.", special: true },
  289: { fact: "289 is the square of 17.", special: true },
  324: { fact: "324 is the square of 18.", special: true },
  343: { fact: "343 is 7 cubed.", special: true },
  360: { fact: "360 is the number of degrees in a full circle.", special: true },
  361: { fact: "361 is the square of 19.", special: true },
  400: { fact: "400 is the square of 20.", special: true },
  441: { fact: "441 is the square of 21.", special: true },
  484: { fact: "484 is the square of 22.", special: true },
  500: { fact: "500 is half of 1000.", special: true },
};

export const genericNumberFacts = {
  14: { fact: "14 is an even composite number and can be written as 2 x 7.", special: false },
  15: { fact: "15 is an odd composite number and can be written as 3 x 5.", special: false },
  17: { fact: "17 is the 7th prime number.", special: false },
  19: { fact: "19 is the 8th prime number.", special: false },
  22: { fact: "22 is an even composite number and can be written as 2 x 11.", special: false },
  23: { fact: "23 is the 9th prime number.", special: false },
  26: { fact: "26 is an even composite number and can be written as 2 x 13.", special: false },
  29: { fact: "29 is the 10th prime number.", special: false },
  31: { fact: "31 is the 11th prime number.", special: false },
  33: { fact: "33 is an odd composite number and can be written as 3 x 11.", special: false },
  34: { fact: "34 is an even composite number and can be written as 2 x 17.", special: false },
  35: { fact: "35 is an odd composite number and can be written as 5 x 7.", special: false },
  37: { fact: "37 is the 12th prime number.", special: false },
  38: { fact: "38 is an even composite number and can be written as 2 x 19.", special: false },
  39: { fact: "39 is an odd composite number and can be written as 3 x 13.", special: false },
  41: { fact: "41 is the 13th prime number.", special: false },
  43: { fact: "43 is the 14th prime number.", special: false },
  44: { fact: "44 is an even composite number and can be written as 2 x 22.", special: false },
  45: { fact: "45 is an odd composite number and can be written as 3 x 15.", special: false },
  46: { fact: "46 is an even composite number and can be written as 2 x 23.", special: false },
  47: { fact: "47 is the 15th prime number.", special: false },
  48: { fact: "48 is an even composite number and can be written as 2 x 24.", special: false },
  51: { fact: "51 is an odd composite number and can be written as 3 x 17.", special: false },
  52: { fact: "52 is an even composite number and can be written as 2 x 26.", special: false },
  53: { fact: "53 is the 16th prime number.", special: false },
  54: { fact: "54 is an even composite number and can be written as 2 x 27.", special: false },
  55: { fact: "55 is an odd composite number and can be written as 5 x 11.", special: false },
  56: { fact: "56 is an even composite number and can be written as 2 x 28.", special: false },
  57: { fact: "57 is an odd composite number and can be written as 3 x 19.", special: false },
  58: { fact: "58 is an even composite number and can be written as 2 x 29.", special: false },
  59: { fact: "59 is the 17th prime number.", special: false },
  61: { fact: "61 is the 18th prime number.", special: false },
  62: { fact: "62 is an even composite number and can be written as 2 x 31.", special: false },
  63: { fact: "63 is an odd composite number and can be written as 3 x 21.", special: false },
  66: { fact: "66 is an even composite number and can be written as 2 x 33.", special: false },
  67: { fact: "67 is the 19th prime number.", special: false },
  68: { fact: "68 is an even composite number and can be written as 2 x 34.", special: false },
  69: { fact: "69 is an odd composite number and can be written as 3 x 23.", special: false },
  70: { fact: "70 is an even composite number and can be written as 2 x 35.", special: false },
  71: { fact: "71 is the 20th prime number.", special: false },
  73: { fact: "73 is the 21st prime number.", special: false },
  74: { fact: "74 is an even composite number and can be written as 2 x 37.", special: false },
  75: { fact: "75 is an odd composite number and can be written as 3 x 25.", special: false },
  76: { fact: "76 is an even composite number and can be written as 2 x 38.", special: false },
  77: { fact: "77 is an odd composite number and can be written as 7 x 11.", special: false },
  78: { fact: "78 is an even composite number and can be written as 2 x 39.", special: false },
  79: { fact: "79 is the 22nd prime number.", special: false },
  80: { fact: "80 is an even composite number and can be written as 2 x 40.", special: false },
  82: { fact: "82 is an even composite number and can be written as 2 x 41.", special: false },
  83: { fact: "83 is the 23rd prime number.", special: false },
  84: { fact: "84 is an even composite number and can be written as 2 x 42.", special: false },
  85: { fact: "85 is an odd composite number and can be written as 5 x 17.", special: false },
  86: { fact: "86 is an even composite number and can be written as 2 x 43.", special: false },
  87: { fact: "87 is an odd composite number and can be written as 3 x 29.", special: false },
  91: { fact: "91 is an odd composite number and can be written as 7 x 13.", special: false },
  92: { fact: "92 is an even composite number and can be written as 2 x 46.", special: false },
  93: { fact: "93 is an odd composite number and can be written as 3 x 31.", special: false },
  94: { fact: "94 is an even composite number and can be written as 2 x 47.", special: false },
  95: { fact: "95 is an odd composite number and can be written as 5 x 19.", special: false },
  97: { fact: "97 is the 25th prime number.", special: false },
  98: { fact: "98 is an even composite number and can be written as 2 x 49.", special: false },
  101: { fact: "101 is the 26th prime number.", special: false },
  102: { fact: "102 is an even composite number and can be written as 2 x 51.", special: false },
  103: { fact: "103 is the 27th prime number.", special: false },
  104: { fact: "104 is an even composite number and can be written as 2 x 52.", special: false },
  105: { fact: "105 is an odd composite number and can be written as 3 x 35.", special: false },
  106: { fact: "106 is an even composite number and can be written as 2 x 53.", special: false },
  107: { fact: "107 is the 28th prime number.", special: false },
  109: { fact: "109 is the 29th prime number.", special: false },
  110: { fact: "110 is an even composite number and can be written as 2 x 55.", special: false },
  112: { fact: "112 is an even composite number and can be written as 2 x 56.", special: false },
  113: { fact: "113 is the 30th prime number.", special: false },
  114: { fact: "114 is an even composite number and can be written as 2 x 57.", special: false },
  115: { fact: "115 is an odd composite number and can be written as 5 x 23.", special: false },
  116: { fact: "116 is an even composite number and can be written as 2 x 58.", special: false },
  117: { fact: "117 is an odd composite number and can be written as 3 x 39.", special: false },
  118: { fact: "118 is an even composite number and can be written as 2 x 59.", special: false },
  119: { fact: "119 is an odd composite number and can be written as 7 x 17.", special: false },
  122: { fact: "122 is an even composite number and can be written as 2 x 61.", special: false },
  123: { fact: "123 is an odd composite number and can be written as 3 x 41.", special: false },
  124: { fact: "124 is an even composite number and can be written as 2 x 62.", special: false },
  126: { fact: "126 is an even composite number and can be written as 2 x 63.", special: false },
  127: { fact: "127 is the 31st prime number.", special: false },
  129: { fact: "129 is an odd composite number and can be written as 3 x 43.", special: false },
  130: { fact: "130 is an even composite number and can be written as 2 x 65.", special: false },
  131: { fact: "131 is the 32nd prime number.", special: false },
  132: { fact: "132 is an even composite number and can be written as 2 x 66.", special: false },
  133: { fact: "133 is an odd composite number and can be written as 7 x 19.", special: false },
  134: { fact: "134 is an even composite number and can be written as 2 x 67.", special: false },
  135: { fact: "135 is an odd composite number and can be written as 3 x 45.", special: false },
  136: { fact: "136 is an even composite number and can be written as 2 x 68.", special: false },
  137: { fact: "137 is the 33rd prime number.", special: false },
  138: { fact: "138 is an even composite number and can be written as 2 x 69.", special: false },
  139: { fact: "139 is the 34th prime number.", special: false },
  140: { fact: "140 is an even composite number and can be written as 2 x 70.", special: false },
  141: { fact: "141 is an odd composite number and can be written as 3 x 47.", special: false },
  142: { fact: "142 is an even composite number and can be written as 2 x 71.", special: false },
  143: { fact: "143 is an odd composite number and can be written as 11 x 13.", special: false },
  145: { fact: "145 is an odd composite number and can be written as 5 x 29.", special: false },
  146: { fact: "146 is an even composite number and can be written as 2 x 73.", special: false },
  147: { fact: "147 is an odd composite number and can be written as 3 x 49.", special: false },
  148: { fact: "148 is an even composite number and can be written as 2 x 74.", special: false },
  149: { fact: "149 is the 35th prime number.", special: false },
  150: { fact: "150 is an even composite number and can be written as 2 x 75.", special: false },
  151: { fact: "151 is the 36th prime number.", special: false },
  152: { fact: "152 is an even composite number and can be written as 2 x 76.", special: false },
  153: { fact: "153 is an odd composite number and can be written as 3 x 51.", special: false },
  154: { fact: "154 is an even composite number and can be written as 2 x 77.", special: false },
  155: { fact: "155 is an odd composite number and can be written as 5 x 31.", special: false },
  156: { fact: "156 is an even composite number and can be written as 2 x 78.", special: false },
  157: { fact: "157 is the 37th prime number.", special: false },
  158: { fact: "158 is an even composite number and can be written as 2 x 79.", special: false },
  159: { fact: "159 is an odd composite number and can be written as 3 x 53.", special: false },
  160: { fact: "160 is an even composite number and can be written as 2 x 80.", special: false },
  161: { fact: "161 is an odd composite number and can be written as 7 x 23.", special: false },
  162: { fact: "162 is an even composite number and can be written as 2 x 81.", special: false },
  163: { fact: "163 is the 38th prime number.", special: false },
  164: { fact: "164 is an even composite number and can be written as 2 x 82.", special: false },
  165: { fact: "165 is an odd composite number and can be written as 3 x 55.", special: false },
  166: { fact: "166 is an even composite number and can be written as 2 x 83.", special: false },
  167: { fact: "167 is the 39th prime number.", special: false },
  168: { fact: "168 is an even composite number and can be written as 2 x 84.", special: false },
  170: { fact: "170 is an even composite number and can be written as 2 x 85.", special: false },
  171: { fact: "171 is an odd composite number and can be written as 3 x 57.", special: false },
  172: { fact: "172 is an even composite number and can be written as 2 x 86.", special: false },
  173: { fact: "173 is the 40th prime number.", special: false },
  174: { fact: "174 is an even composite number and can be written as 2 x 87.", special: false },
  175: { fact: "175 is an odd composite number and can be written as 5 x 35.", special: false },
  176: { fact: "176 is an even composite number and can be written as 2 x 88.", special: false },
  177: { fact: "177 is an odd composite number and can be written as 3 x 59.", special: false },
  178: { fact: "178 is an even composite number and can be written as 2 x 89.", special: false },
  179: { fact: "179 is the 41st prime number.", special: false },
  181: { fact: "181 is the 42nd prime number.", special: false },
  182: { fact: "182 is an even composite number and can be written as 2 x 91.", special: false },
  183: { fact: "183 is an odd composite number and can be written as 3 x 61.", special: false },
  184: { fact: "184 is an even composite number and can be written as 2 x 92.", special: false },
  185: { fact: "185 is an odd composite number and can be written as 5 x 37.", special: false },
  186: { fact: "186 is an even composite number and can be written as 2 x 93.", special: false },
  187: { fact: "187 is an odd composite number and can be written as 11 x 17.", special: false },
  188: { fact: "188 is an even composite number and can be written as 2 x 94.", special: false },
  189: { fact: "189 is an odd composite number and can be written as 3 x 63.", special: false },
  190: { fact: "190 is an even composite number and can be written as 2 x 95.", special: false },
  191: { fact: "191 is the 43rd prime number.", special: false },
  192: { fact: "192 is an even composite number and can be written as 2 x 96.", special: false },
  193: { fact: "193 is the 44th prime number.", special: false },
  194: { fact: "194 is an even composite number and can be written as 2 x 97.", special: false },
  195: { fact: "195 is an odd composite number and can be written as 3 x 65.", special: false },
  197: { fact: "197 is the 45th prime number.", special: false },
  198: { fact: "198 is an even composite number and can be written as 2 x 99.", special: false },
  199: { fact: "199 is the 46th prime number.", special: false },
  201: { fact: "201 is an odd composite number and can be written as 3 x 67.", special: false },
  202: { fact: "202 is an even composite number and can be written as 2 x 101.", special: false },
  203: { fact: "203 is an odd composite number and can be written as 7 x 29.", special: false },
  204: { fact: "204 is an even composite number and can be written as 2 x 102.", special: false },
  205: { fact: "205 is an odd composite number and can be written as 5 x 41.", special: false },
  206: { fact: "206 is an even composite number and can be written as 2 x 103.", special: false },
  207: { fact: "207 is an odd composite number and can be written as 3 x 69.", special: false },
  208: { fact: "208 is an even composite number and can be written as 2 x 104.", special: false },
  209: { fact: "209 is an odd composite number and can be written as 11 x 19.", special: false },
  210: { fact: "210 is an even composite number and can be written as 2 x 105.", special: false },
  211: { fact: "211 is the 47th prime number.", special: false },
  212: { fact: "212 is an even composite number and can be written as 2 x 106.", special: false },
  213: { fact: "213 is an odd composite number and can be written as 3 x 71.", special: false },
  214: { fact: "214 is an even composite number and can be written as 2 x 107.", special: false },
  215: { fact: "215 is an odd composite number and can be written as 5 x 43.", special: false },
  216: { fact: "216 is an even composite number and can be written as 2 x 108.", special: false },
  217: { fact: "217 is an odd composite number and can be written as 7 x 31.", special: false },
  218: { fact: "218 is an even composite number and can be written as 2 x 109.", special: false },
  219: { fact: "219 is an odd composite number and can be written as 3 x 73.", special: false },
  220: { fact: "220 is an even composite number and can be written as 2 x 110.", special: false },
  221: { fact: "221 is an odd composite number and can be written as 13 x 17.", special: false },
  222: { fact: "222 is an even composite number and can be written as 2 x 111.", special: false },
  223: { fact: "223 is the 48th prime number.", special: false },
  224: { fact: "224 is an even composite number and can be written as 2 x 112.", special: false },
  226: { fact: "226 is an even composite number and can be written as 2 x 113.", special: false },
  227: { fact: "227 is the 49th prime number.", special: false },
  228: { fact: "228 is an even composite number and can be written as 2 x 114.", special: false },
  229: { fact: "229 is the 50th prime number.", special: false },
  230: { fact: "230 is an even composite number and can be written as 2 x 115.", special: false },
  231: { fact: "231 is an odd composite number and can be written as 3 x 77.", special: false },
  232: { fact: "232 is an even composite number and can be written as 2 x 116.", special: false },
  233: { fact: "233 is the 51st prime number.", special: false },
  234: { fact: "234 is an even composite number and can be written as 2 x 117.", special: false },
  235: { fact: "235 is an odd composite number and can be written as 5 x 47.", special: false },
  236: { fact: "236 is an even composite number and can be written as 2 x 118.", special: false },
  237: { fact: "237 is an odd composite number and can be written as 3 x 79.", special: false },
  238: { fact: "238 is an even composite number and can be written as 2 x 119.", special: false },
  239: { fact: "239 is the 52nd prime number.", special: false },
  240: { fact: "240 is an even composite number and can be written as 2 x 120.", special: false },
  241: { fact: "241 is the 53rd prime number.", special: false },
  242: { fact: "242 is an even composite number and can be written as 2 x 121.", special: false },
  244: { fact: "244 is an even composite number and can be written as 2 x 122.", special: false },
  245: { fact: "245 is an odd composite number and can be written as 5 x 49.", special: false },
  246: { fact: "246 is an even composite number and can be written as 2 x 123.", special: false },
  247: { fact: "247 is an odd composite number and can be written as 13 x 19.", special: false },
  248: { fact: "248 is an even composite number and can be written as 2 x 124.", special: false },
  249: { fact: "249 is an odd composite number and can be written as 3 x 83.", special: false },
  250: { fact: "250 is an even composite number and can be written as 2 x 125.", special: false },
  251: { fact: "251 is the 54th prime number.", special: false },
  252: { fact: "252 is an even composite number and can be written as 2 x 126.", special: false },
  253: { fact: "253 is an odd composite number and can be written as 11 x 23.", special: false },
  254: { fact: "254 is an even composite number and can be written as 2 x 127.", special: false },
  255: { fact: "255 is an odd composite number and can be written as 3 x 85.", special: false },
  257: { fact: "257 is the 55th prime number.", special: false },
  258: { fact: "258 is an even composite number and can be written as 2 x 129.", special: false },
  259: { fact: "259 is an odd composite number and can be written as 7 x 37.", special: false },
  260: { fact: "260 is an even composite number and can be written as 2 x 130.", special: false },
  261: { fact: "261 is an odd composite number and can be written as 3 x 87.", special: false },
  262: { fact: "262 is an even composite number and can be written as 2 x 131.", special: false },
  263: { fact: "263 is the 56th prime number.", special: false },
  264: { fact: "264 is an even composite number and can be written as 2 x 132.", special: false },
  265: { fact: "265 is an odd composite number and can be written as 5 x 53.", special: false },
  266: { fact: "266 is an even composite number and can be written as 2 x 133.", special: false },
  267: { fact: "267 is an odd composite number and can be written as 3 x 89.", special: false },
  268: { fact: "268 is an even composite number and can be written as 2 x 134.", special: false },
  269: { fact: "269 is the 57th prime number.", special: false },
  270: { fact: "270 is an even composite number and can be written as 2 x 135.", special: false },
  271: { fact: "271 is the 58th prime number.", special: false },
  272: { fact: "272 is an even composite number and can be written as 2 x 136.", special: false },
  273: { fact: "273 is an odd composite number and can be written as 3 x 91.", special: false },
  274: { fact: "274 is an even composite number and can be written as 2 x 137.", special: false },
  275: { fact: "275 is an odd composite number and can be written as 5 x 55.", special: false },
  276: { fact: "276 is an even composite number and can be written as 2 x 138.", special: false },
  277: { fact: "277 is the 59th prime number.", special: false },
  278: { fact: "278 is an even composite number and can be written as 2 x 139.", special: false },
  279: { fact: "279 is an odd composite number and can be written as 3 x 93.", special: false },
  280: { fact: "280 is an even composite number and can be written as 2 x 140.", special: false },
  281: { fact: "281 is the 60th prime number.", special: false },
  282: { fact: "282 is an even composite number and can be written as 2 x 141.", special: false },
  283: { fact: "283 is the 61st prime number.", special: false },
  284: { fact: "284 is an even composite number and can be written as 2 x 142.", special: false },
  285: { fact: "285 is an odd composite number and can be written as 3 x 95.", special: false },
  286: { fact: "286 is an even composite number and can be written as 2 x 143.", special: false },
  287: { fact: "287 is an odd composite number and can be written as 7 x 41.", special: false },
  288: { fact: "288 is an even composite number and can be written as 2 x 144.", special: false },
  290: { fact: "290 is an even composite number and can be written as 2 x 145.", special: false },
  291: { fact: "291 is an odd composite number and can be written as 3 x 97.", special: false },
  292: { fact: "292 is an even composite number and can be written as 2 x 146.", special: false },
  293: { fact: "293 is the 62nd prime number.", special: false },
  294: { fact: "294 is an even composite number and can be written as 2 x 147.", special: false },
  295: { fact: "295 is an odd composite number and can be written as 5 x 59.", special: false },
  296: { fact: "296 is an even composite number and can be written as 2 x 148.", special: false },
  297: { fact: "297 is an odd composite number and can be written as 3 x 99.", special: false },
  298: { fact: "298 is an even composite number and can be written as 2 x 149.", special: false },
  299: { fact: "299 is an odd composite number and can be written as 13 x 23.", special: false },
  300: { fact: "300 is an even composite number and can be written as 2 x 150.", special: false },
  301: { fact: "301 is an odd composite number and can be written as 7 x 43.", special: false },
  302: { fact: "302 is an even composite number and can be written as 2 x 151.", special: false },
  303: { fact: "303 is an odd composite number and can be written as 3 x 101.", special: false },
  304: { fact: "304 is an even composite number and can be written as 2 x 152.", special: false },
  305: { fact: "305 is an odd composite number and can be written as 5 x 61.", special: false },
  306: { fact: "306 is an even composite number and can be written as 2 x 153.", special: false },
  307: { fact: "307 is the 63rd prime number.", special: false },
  308: { fact: "308 is an even composite number and can be written as 2 x 154.", special: false },
  309: { fact: "309 is an odd composite number and can be written as 3 x 103.", special: false },
  310: { fact: "310 is an even composite number and can be written as 2 x 155.", special: false },
  311: { fact: "311 is the 64th prime number.", special: false },
  312: { fact: "312 is an even composite number and can be written as 2 x 156.", special: false },
  313: { fact: "313 is the 65th prime number.", special: false },
  314: { fact: "314 is an even composite number and can be written as 2 x 157.", special: false },
  315: { fact: "315 is an odd composite number and can be written as 3 x 105.", special: false },
  316: { fact: "316 is an even composite number and can be written as 2 x 158.", special: false },
  317: { fact: "317 is the 66th prime number.", special: false },
  318: { fact: "318 is an even composite number and can be written as 2 x 159.", special: false },
  319: { fact: "319 is an odd composite number and can be written as 11 x 29.", special: false },
  320: { fact: "320 is an even composite number and can be written as 2 x 160.", special: false },
  321: { fact: "321 is an odd composite number and can be written as 3 x 107.", special: false },
  322: { fact: "322 is an even composite number and can be written as 2 x 161.", special: false },
  323: { fact: "323 is an odd composite number and can be written as 17 x 19.", special: false },
  325: { fact: "325 is an odd composite number and can be written as 5 x 65.", special: false },
  326: { fact: "326 is an even composite number and can be written as 2 x 163.", special: false },
  327: { fact: "327 is an odd composite number and can be written as 3 x 109.", special: false },
  328: { fact: "328 is an even composite number and can be written as 2 x 164.", special: false },
  329: { fact: "329 is an odd composite number and can be written as 7 x 47.", special: false },
  330: { fact: "330 is an even composite number and can be written as 2 x 165.", special: false },
  331: { fact: "331 is the 67th prime number.", special: false },
  332: { fact: "332 is an even composite number and can be written as 2 x 166.", special: false },
  333: { fact: "333 is an odd composite number and can be written as 3 x 111.", special: false },
  334: { fact: "334 is an even composite number and can be written as 2 x 167.", special: false },
  335: { fact: "335 is an odd composite number and can be written as 5 x 67.", special: false },
  336: { fact: "336 is an even composite number and can be written as 2 x 168.", special: false },
  337: { fact: "337 is the 68th prime number.", special: false },
  338: { fact: "338 is an even composite number and can be written as 2 x 169.", special: false },
  339: { fact: "339 is an odd composite number and can be written as 3 x 113.", special: false },
  340: { fact: "340 is an even composite number and can be written as 2 x 170.", special: false },
  341: { fact: "341 is an odd composite number and can be written as 11 x 31.", special: false },
  342: { fact: "342 is an even composite number and can be written as 2 x 171.", special: false },
  344: { fact: "344 is an even composite number and can be written as 2 x 172.", special: false },
  345: { fact: "345 is an odd composite number and can be written as 3 x 115.", special: false },
  346: { fact: "346 is an even composite number and can be written as 2 x 173.", special: false },
  347: { fact: "347 is the 69th prime number.", special: false },
  348: { fact: "348 is an even composite number and can be written as 2 x 174.", special: false },
  349: { fact: "349 is the 70th prime number.", special: false },
  350: { fact: "350 is an even composite number and can be written as 2 x 175.", special: false },
  351: { fact: "351 is an odd composite number and can be written as 3 x 117.", special: false },
  352: { fact: "352 is an even composite number and can be written as 2 x 176.", special: false },
  353: { fact: "353 is the 71st prime number.", special: false },
  354: { fact: "354 is an even composite number and can be written as 2 x 177.", special: false },
  355: { fact: "355 is an odd composite number and can be written as 5 x 71.", special: false },
  356: { fact: "356 is an even composite number and can be written as 2 x 178.", special: false },
  357: { fact: "357 is an odd composite number and can be written as 3 x 119.", special: false },
  358: { fact: "358 is an even composite number and can be written as 2 x 179.", special: false },
  359: { fact: "359 is the 72nd prime number.", special: false },
  362: { fact: "362 is an even composite number and can be written as 2 x 181.", special: false },
  363: { fact: "363 is an odd composite number and can be written as 3 x 121.", special: false },
  364: { fact: "364 is an even composite number and can be written as 2 x 182.", special: false },
  365: { fact: "365 is an odd composite number and can be written as 5 x 73.", special: false },
  366: { fact: "366 is an even composite number and can be written as 2 x 183.", special: false },
  367: { fact: "367 is the 73rd prime number.", special: false },
  368: { fact: "368 is an even composite number and can be written as 2 x 184.", special: false },
  369: { fact: "369 is an odd composite number and can be written as 3 x 123.", special: false },
  370: { fact: "370 is an even composite number and can be written as 2 x 185.", special: false },
  371: { fact: "371 is an odd composite number and can be written as 7 x 53.", special: false },
  372: { fact: "372 is an even composite number and can be written as 2 x 186.", special: false },
  373: { fact: "373 is the 74th prime number.", special: false },
  374: { fact: "374 is an even composite number and can be written as 2 x 187.", special: false },
  375: { fact: "375 is an odd composite number and can be written as 3 x 125.", special: false },
  376: { fact: "376 is an even composite number and can be written as 2 x 188.", special: false },
  377: { fact: "377 is an odd composite number and can be written as 13 x 29.", special: false },
  378: { fact: "378 is an even composite number and can be written as 2 x 189.", special: false },
  379: { fact: "379 is the 75th prime number.", special: false },
  380: { fact: "380 is an even composite number and can be written as 2 x 190.", special: false },
  381: { fact: "381 is an odd composite number and can be written as 3 x 127.", special: false },
  382: { fact: "382 is an even composite number and can be written as 2 x 191.", special: false },
  383: { fact: "383 is the 76th prime number.", special: false },
  384: { fact: "384 is an even composite number and can be written as 2 x 192.", special: false },
  385: { fact: "385 is an odd composite number and can be written as 5 x 77.", special: false },
  386: { fact: "386 is an even composite number and can be written as 2 x 193.", special: false },
  387: { fact: "387 is an odd composite number and can be written as 3 x 129.", special: false },
  388: { fact: "388 is an even composite number and can be written as 2 x 194.", special: false },
  389: { fact: "389 is the 77th prime number.", special: false },
  390: { fact: "390 is an even composite number and can be written as 2 x 195.", special: false },
  391: { fact: "391 is an odd composite number and can be written as 17 x 23.", special: false },
  392: { fact: "392 is an even composite number and can be written as 2 x 196.", special: false },
  393: { fact: "393 is an odd composite number and can be written as 3 x 131.", special: false },
  394: { fact: "394 is an even composite number and can be written as 2 x 197.", special: false },
  395: { fact: "395 is an odd composite number and can be written as 5 x 79.", special: false },
  396: { fact: "396 is an even composite number and can be written as 2 x 198.", special: false },
  397: { fact: "397 is the 78th prime number.", special: false },
  398: { fact: "398 is an even composite number and can be written as 2 x 199.", special: false },
  399: { fact: "399 is an odd composite number and can be written as 3 x 133.", special: false },
  401: { fact: "401 is the 79th prime number.", special: false },
  402: { fact: "402 is an even composite number and can be written as 2 x 201.", special: false },
  403: { fact: "403 is an odd composite number and can be written as 13 x 31.", special: false },
  404: { fact: "404 is an even composite number and can be written as 2 x 202.", special: false },
  405: { fact: "405 is an odd composite number and can be written as 3 x 135.", special: false },
  406: { fact: "406 is an even composite number and can be written as 2 x 203.", special: false },
  407: { fact: "407 is an odd composite number and can be written as 11 x 37.", special: false },
  408: { fact: "408 is an even composite number and can be written as 2 x 204.", special: false },
  409: { fact: "409 is the 80th prime number.", special: false },
  410: { fact: "410 is an even composite number and can be written as 2 x 205.", special: false },
  411: { fact: "411 is an odd composite number and can be written as 3 x 137.", special: false },
  412: { fact: "412 is an even composite number and can be written as 2 x 206.", special: false },
  413: { fact: "413 is an odd composite number and can be written as 7 x 59.", special: false },
  414: { fact: "414 is an even composite number and can be written as 2 x 207.", special: false },
  415: { fact: "415 is an odd composite number and can be written as 5 x 83.", special: false },
  416: { fact: "416 is an even composite number and can be written as 2 x 208.", special: false },
  417: { fact: "417 is an odd composite number and can be written as 3 x 139.", special: false },
  418: { fact: "418 is an even composite number and can be written as 2 x 209.", special: false },
  419: { fact: "419 is the 81st prime number.", special: false },
  420: { fact: "420 is an even composite number and can be written as 2 x 210.", special: false },
  421: { fact: "421 is the 82nd prime number.", special: false },
  422: { fact: "422 is an even composite number and can be written as 2 x 211.", special: false },
  423: { fact: "423 is an odd composite number and can be written as 3 x 141.", special: false },
  424: { fact: "424 is an even composite number and can be written as 2 x 212.", special: false },
  425: { fact: "425 is an odd composite number and can be written as 5 x 85.", special: false },
  426: { fact: "426 is an even composite number and can be written as 2 x 213.", special: false },
  427: { fact: "427 is an odd composite number and can be written as 7 x 61.", special: false },
  428: { fact: "428 is an even composite number and can be written as 2 x 214.", special: false },
  429: { fact: "429 is an odd composite number and can be written as 3 x 143.", special: false },
  430: { fact: "430 is an even composite number and can be written as 2 x 215.", special: false },
  431: { fact: "431 is the 83rd prime number.", special: false },
  432: { fact: "432 is an even composite number and can be written as 2 x 216.", special: false },
  433: { fact: "433 is the 84th prime number.", special: false },
  434: { fact: "434 is an even composite number and can be written as 2 x 217.", special: false },
  435: { fact: "435 is an odd composite number and can be written as 3 x 145.", special: false },
  436: { fact: "436 is an even composite number and can be written as 2 x 218.", special: false },
  437: { fact: "437 is an odd composite number and can be written as 19 x 23.", special: false },
  438: { fact: "438 is an even composite number and can be written as 2 x 219.", special: false },
  439: { fact: "439 is the 85th prime number.", special: false },
  440: { fact: "440 is an even composite number and can be written as 2 x 220.", special: false },
  442: { fact: "442 is an even composite number and can be written as 2 x 221.", special: false },
  443: { fact: "443 is the 86th prime number.", special: false },
  444: { fact: "444 is an even composite number and can be written as 2 x 222.", special: false },
  445: { fact: "445 is an odd composite number and can be written as 5 x 89.", special: false },
  446: { fact: "446 is an even composite number and can be written as 2 x 223.", special: false },
  447: { fact: "447 is an odd composite number and can be written as 3 x 149.", special: false },
  448: { fact: "448 is an even composite number and can be written as 2 x 224.", special: false },
  449: { fact: "449 is the 87th prime number.", special: false },
  450: { fact: "450 is an even composite number and can be written as 2 x 225.", special: false },
  451: { fact: "451 is an odd composite number and can be written as 11 x 41.", special: false },
  452: { fact: "452 is an even composite number and can be written as 2 x 226.", special: false },
  453: { fact: "453 is an odd composite number and can be written as 3 x 151.", special: false },
  454: { fact: "454 is an even composite number and can be written as 2 x 227.", special: false },
  455: { fact: "455 is an odd composite number and can be written as 5 x 91.", special: false },
  456: { fact: "456 is an even composite number and can be written as 2 x 228.", special: false },
  457: { fact: "457 is the 88th prime number.", special: false },
  458: { fact: "458 is an even composite number and can be written as 2 x 229.", special: false },
  459: { fact: "459 is an odd composite number and can be written as 3 x 153.", special: false },
  460: { fact: "460 is an even composite number and can be written as 2 x 230.", special: false },
  461: { fact: "461 is the 89th prime number.", special: false },
  462: { fact: "462 is an even composite number and can be written as 2 x 231.", special: false },
  463: { fact: "463 is the 90th prime number.", special: false },
  464: { fact: "464 is an even composite number and can be written as 2 x 232.", special: false },
  465: { fact: "465 is an odd composite number and can be written as 3 x 155.", special: false },
  466: { fact: "466 is an even composite number and can be written as 2 x 233.", special: false },
  467: { fact: "467 is the 91st prime number.", special: false },
  468: { fact: "468 is an even composite number and can be written as 2 x 234.", special: false },
  469: { fact: "469 is an odd composite number and can be written as 7 x 67.", special: false },
  470: { fact: "470 is an even composite number and can be written as 2 x 235.", special: false },
  471: { fact: "471 is an odd composite number and can be written as 3 x 157.", special: false },
  472: { fact: "472 is an even composite number and can be written as 2 x 236.", special: false },
  473: { fact: "473 is an odd composite number and can be written as 11 x 43.", special: false },
  474: { fact: "474 is an even composite number and can be written as 2 x 237.", special: false },
  475: { fact: "475 is an odd composite number and can be written as 5 x 95.", special: false },
  476: { fact: "476 is an even composite number and can be written as 2 x 238.", special: false },
  477: { fact: "477 is an odd composite number and can be written as 3 x 159.", special: false },
  478: { fact: "478 is an even composite number and can be written as 2 x 239.", special: false },
  479: { fact: "479 is the 92nd prime number.", special: false },
  480: { fact: "480 is an even composite number and can be written as 2 x 240.", special: false },
  481: { fact: "481 is an odd composite number and can be written as 13 x 37.", special: false },
  482: { fact: "482 is an even composite number and can be written as 2 x 241.", special: false },
  483: { fact: "483 is an odd composite number and can be written as 3 x 161.", special: false },
  485: { fact: "485 is an odd composite number and can be written as 5 x 97.", special: false },
  486: { fact: "486 is an even composite number and can be written as 2 x 243.", special: false },
  487: { fact: "487 is the 93rd prime number.", special: false },
  488: { fact: "488 is an even composite number and can be written as 2 x 244.", special: false },
  489: { fact: "489 is an odd composite number and can be written as 3 x 163.", special: false },
  490: { fact: "490 is an even composite number and can be written as 2 x 245.", special: false },
  491: { fact: "491 is the 94th prime number.", special: false },
  492: { fact: "492 is an even composite number and can be written as 2 x 246.", special: false },
  493: { fact: "493 is an odd composite number and can be written as 17 x 29.", special: false },
  494: { fact: "494 is an even composite number and can be written as 2 x 247.", special: false },
  495: { fact: "495 is an odd composite number and can be written as 3 x 165.", special: false },
  496: { fact: "496 is an even composite number and can be written as 2 x 248.", special: false },
  497: { fact: "497 is an odd composite number and can be written as 7 x 71.", special: false },
  498: { fact: "498 is an even composite number and can be written as 2 x 249.", special: false },
  499: { fact: "499 is the 95th prime number.", special: false },
};

export const numberFacts = {};
for (let n = 1; n <= 500; n += 1) {
  const entry = specialNumberFacts[n] || genericNumberFacts[n];
  numberFacts[n] = [entry.fact];
}

export function getNumberFactEntry(n) {
  if (specialNumberFacts[n]) return specialNumberFacts[n];
  if (genericNumberFacts[n]) return genericNumberFacts[n];
  return { fact: `${n} is a number in this game.`, special: false };
}

export function getNumberFact(n) {
  return getNumberFactEntry(n).fact;
}
